<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>283c9dc9-7c95-4fbe-a2f9-7491b2d9903a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.slp-btn.navigation-item-top.slp-mr-24.slp-btn-ghost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='be-navigation-desktop']/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93ccf810-4178-4ecf-b11b-e94f9ec63982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gitlab.com/users/sign_up/</value>
      <webElementGuid>a33f2ed0-a1aa-4fea-be68-43e2df8d2539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>5d37d88d-2b99-433d-80ec-b13c9648c48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>bb84d61e-a758-4ea3-9e89-a2789b19d85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slp-btn navigation-item-top slp-mr-24 slp-btn-ghost</value>
      <webElementGuid>b4a1963c-1031-4d1a-aaf3-38b918af32b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Register </value>
      <webElementGuid>92b493b7-c6ba-468e-aa5a-145b13eaa92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be-navigation-desktop&quot;)/div[@class=&quot;navigation&quot;]/div[@class=&quot;navigation-top&quot;]/a[@class=&quot;slp-btn navigation-item-top slp-mr-24 slp-btn-ghost&quot;]</value>
      <webElementGuid>61dc6eaa-7236-4863-8ceb-8ec9afa74382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='be-navigation-desktop']/div/div/a[2]</value>
      <webElementGuid>a66c8d70-2da9-4d55-8ad5-d00bfef4aa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>49479db1-0b98-4409-8b15-1cce9eb2104b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::a[1]</value>
      <webElementGuid>00025f04-86e5-44a8-ae9b-10347385283c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>94b606a0-fb75-4656-88d7-6b81c9c7efb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why GitLab'])[1]/preceding::a[2]</value>
      <webElementGuid>faf6a090-ce4f-4fa9-af09-f9c7860b198a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[1]/preceding::a[2]</value>
      <webElementGuid>64efe35c-7712-40ef-9965-c06b257e6b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>8368df2f-9f6f-4b35-961e-e66fde60f82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://gitlab.com/users/sign_up/')]</value>
      <webElementGuid>8c5b0290-d47e-496d-9728-6227be0dd460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>eca0bb10-d651-450a-9477-95c0ec3865ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gitlab.com/users/sign_up/' and @title = 'Register' and (text() = ' Register ' or . = ' Register ')]</value>
      <webElementGuid>5fcbed7b-9bff-45f0-8ece-903403932a3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
