<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Authorize gitlabhq</name>
   <tag></tag>
   <elementGuidId>3ef5f5cc-9932-4d01-acef-dd999b123946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-oauth-authorize-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-oauth-authorize-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8841ea42-57cc-4080-b0f0-6b72f2a69b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-click</name>
      <type>Main</type>
      <value>oauth_application_authorization</value>
      <webElementGuid>4bd680cd-5306-4fbc-b4b3-2b4d88e656b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-dimensions</name>
      <type>Main</type>
      <value>marketplace_listing_id:,came_from_marketplace:false,paid_marketplace_plan_purchased:false</value>
      <webElementGuid>35462377-6a00-4ee6-9d10-daed02e93001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-click</name>
      <type>Main</type>
      <value>Oauth, oauth application authorized, oauth_application_id:62872; listing_id:; came_from_integrations_directory:false; came_from_marketplace:false; paid_marketplace_plan_purchased:false; marketplace_listing_id:</value>
      <webElementGuid>1cbb2432-1d65-4646-89d5-6e431ce87682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fc339e85-0be9-47db-8a0e-f6bb6f0ec1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authorize</value>
      <webElementGuid>10388a3d-9933-44f5-b30f-9b7c07234afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>046325e3-dfb8-4bbe-b453-62082d549f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-oauth-authorize-btn</value>
      <webElementGuid>6915d283-7ed9-443d-9935-ae6af04428bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary width-full ws-normal</value>
      <webElementGuid>d3cbca51-d1e2-4175-a990-5a3bb2a49f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorize gitlabhq</value>
      <webElementGuid>18604962-514f-4b7b-b9e9-e5b118283fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-oauth-authorize-btn&quot;)</value>
      <webElementGuid>8fe0b20a-4ee5-455c-8af3-d6ac7e29db79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-oauth-authorize-btn']</value>
      <webElementGuid>6d13a7f8-1529-4992-a1db-8505eacf4bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-pjax-container']/div/div[2]/div/div[2]/div/form/div/button[2]</value>
      <webElementGuid>21ff620f-bbd3-4265-93fa-255a58af1cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>b13360b9-f32f-421b-8141-119f31be6743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[2]</value>
      <webElementGuid>1fa72970-78f7-46e7-8abe-e66467aaa22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://gitlab.com'])[1]/preceding::button[1]</value>
      <webElementGuid>4ea3b0e5-e72b-4847-8ab3-7f299aca6b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Authorize gitlabhq']/parent::*</value>
      <webElementGuid>b4b2ed1b-c903-4295-b5ce-8a7623ae9a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>58285d8d-971f-41dc-93a9-ea85fb8bebdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'authorize' and @id = 'js-oauth-authorize-btn' and (text() = 'Authorize gitlabhq' or . = 'Authorize gitlabhq')]</value>
      <webElementGuid>c8c68954-b1c3-4a85-97d3-b1efaea5d7f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
